version: '3.9'

services:
    pg_channel_tmp:
        image: postgres
        env_file: .env
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB"]
            retries: 3
            interval: 3s
            timeout: 3s
        restart: always

    django_channel_tmp:
        build: ./
        env_file: .env
        ports:
            - 3000:3000
        volumes:
            - ./:/var/www
        depends_on:
            pg_channel_tmp:
                condition: service_healthy

        command: bash -f ./run.sh